In [1]:
import numpy as np

In [2]:
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [4]:
a = np.arange(15).reshape(5,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [5]:
a.shape

2

In [6]:
a.dtype

dtype('int64')

In [7]:
a.ndim

2

In [1]:
import numpy as np
import time
import sys

#list vs numpy array

In [20]:
# size of 1000 int elements in list

In [21]:
l = range(1000)
print(sys.getsizeof(1)*len(l))

28000


In [22]:
# size of 1000 int objects in numpy

In [ ]:
a = np.arange(1000)
print(a.size * a.itemsize)

In [2]:
SIZE = 10000000

l1 = range(SIZE)
l2 = range(SIZE)

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("List took : ", (time.time()-start))

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

start = time.time()
aresult = a1+a2
print("Numpy took : ", (time.time()-start))

List took :  1.1045727729797363
Numpy took :  0.04805803298950195


In [3]:
a = np.array([[2,3],[3,6],[8,0]])

In [5]:
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)

[[2 3]
 [3 6]
 [8 0]]
(3, 2)
2
int64
6


In [6]:
print(np.zeros((3,4)))

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [7]:
print(np.ones((2,6)))

[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


In [8]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [9]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [11]:
print(np.arange(1,10,3))

[1 4 7]


In [12]:
print(np.linspace(1,5,10))

[ 1.          1.44444444  1.88888889  2.33333333  2.77777778  3.22222222
  3.66666667  4.11111111  4.55555556  5.        ]


In [13]:
print(np.linspace(1,5,5))

[ 1.  2.  3.  4.  5.]


In [14]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [17]:
print(a.reshape(6,1))
print(a.reshape(2,3))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3]
 [4 5 6]]


In [19]:
print(a.ravel())

[1 2 3 4 5 6]


In [24]:
print(a.min())
print(a.max())

1
6


In [29]:
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

[[1 2]
 [3 4]
 [5 6]]
21
[ 9 12]
[ 3  7 11]


In [6]:
a = np.arange(12).reshape(3,4)
b= np.arange(12).reshape(3,4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
add = a+b
sub = a-b
mult = a*b
div = a /b
print(add)
print(sub)
print(mult)
print(div)

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
[[ nan   1.   1.   1.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]]


/Users/avanish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [15]:
a = np.arange(9).reshape(3,3)
b = np.arange(9).reshape(3,3)
print(a.dot(b))


[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [16]:
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [17]:
print(a[2])

[6 7 8]


In [18]:
print(a[-1])

[6 7 8]


In [19]:
print(a[:,1])

[1 4 7]


In [21]:
print(a[1,:])

[3 4 5]


In [22]:
for row in a:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [23]:
for cell in a.flat:
    print(cell)

0
1
2
3
4
5
6
7
8


In [24]:
print(a)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [31]:
v = np.vstack((a,b))
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
h = np.hstack((a,b))
print(h)

[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [6 7 8 6 7 8]]


In [41]:
p = np.arange(30).reshape(2,15)
print(p)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [46]:
hs = np.hsplit(p,3)
print(hs)

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]


In [47]:
vs = np.vsplit(p,2)
print(vs)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]


In [48]:
a= np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [49]:
b = a > 4
print(b)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [50]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [55]:
a[b]=-1
a[b]

array([-1, -1, -1, -1, -1, -1, -1])